CREATE TABLE IF NOT EXISTS department_info
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    department_name VARCHAR(255),
    staff_quantity INTEGER,
    department_director VARCHAR(255),
    module_id BIGINT REFERENCES module_info(id)
);